algoritmo "estrutura-de-repetic?o-simples(tutorial)"
var
   C, U: inteiro
inicio
C <- 0 //Esta variavel ira receber o numero 0.
enquanto (C <= 10) faca // 10 ser? o limete das repeticoes.
  escreval(C)// A variavel pegou 0 de cima, que nesse caso sera 0.
C <- C + 1 // O C que esta somando com 0, e o C que esta recebendo, agora e 1.
fimenquanto // chegando aqui cera reiniciado, at? que chegue ao numero 10,
//ou outro numero que voce escreva(faca o teste!;)

fimalgoritmo